### ISSUE TITLE
[Story] Display basic projects

### ISSUE THREAD

**Issue by constantingoeldel** [constantingoeldel/capstone-project#1]
# Value statement

As a **user**
I need to **see projects**
so that **I can gather information on them**

# Description (Text, Scribble, Wireframe, Design)
<img width="567" alt="image" src="https://user-images.githubusercontent.com/67916925/91305647-9e54c180-e7ab-11ea-9523-494763d64686.png">

-  Displays the most rudimentary possible, yet still usable project-cards to the user
-  Information includes a picture of the project, the project title and location, as well as a short description.

# Acceptance criteria

- [x] Displays multiple cards generated from a dataset 
- [x] Each card follows the design, no abbreviations
- [x] Pictures are same size
- [x] Cards have same width, slightly differing length due to text differences

# Tasks

- [x] Initialize React App
- [x] Create `Project` Component
- [x] Create `ProjectHeadline` Component (consisting of project-title and location)
- [x] Link image based from public dir
- [x] Create mock dataset (`db.json`) 
- [x] Render each element of the database (`.map()`)
- [ ] Tests

# Complexity
Small
