### ISSUE TITLE
[Story] Project detail view

### ISSUE THREAD

**Issue by constantingoeldel** [constantingoeldel/capstone-project#11]
# Value statement

As a user
I need to see additional information about a project
so that I can find out more about it

# Description (Text, Scribble, Wireframe, Design)

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/67916925/92366847-f7025380-f0f5-11ea-9038-6256c3ac7581.png">

-  Upon click on a project, a card scoots up from the bottom and overlays the screen
-  It shows additional content such as affiliated people, company information, comments and updates

# Acceptance criteria

- [x] Detail page overlays blurred background
- [x] Press on back removes page
- [x] Information sections are expandable
- [ ] People section overlaps when over a certain number
- [ ] Page rises from the lower edge of the screen
Animations will be handled in the next story

# Tasks

- [x] TESTS 
- [x] Storybook
- [x] Create Overlay component -> receives all necessary project data
- [x] toggle on project click
- [x] people section
- [x] information section

# Complexity
medium
