### ISSUE TITLE
[Story] Add animations

### ISSUE THREAD

**Issue by constantingoeldel** [constantingoeldel/capstone-project#15]
# Value statement

As a user
I need to have a UX that feels good
so that I come back to the app

# Description (Text, Scribble, Wireframe, Design)

-  Add simple animations when opening, clicking and swiping
-  Give the app a natural feeling

# Acceptance criteria

- [x] Overlay slides up and down
- [x] Slide down closes overlay as well
- [x] Details slowly open, `+` spins to `x`
- [x] Performance is upheld
- [x] General CSS overhaul

# Tasks

- [x] TESTS 
- [x] Storybook
- [x] React Spring  & React Swipeable
- [x] Scrolling on mobile works as intended
- [x] React measure for auto height

# Complexity
low
