### ISSUE TITLE
[Story] Filter Projects by tags

### ISSUE THREAD

**Issue by constantingoeldel** [constantingoeldel/capstone-project#2]
# Value statement

As a **user**
I need to **filter project by tags**
so that I can **find personally suiting projects** 

# Description (Text, Scribble, Wireframe, Design)

<img width="703" alt="image" src="https://user-images.githubusercontent.com/67916925/91309898-7cf6d400-e7b1-11ea-8e40-eb6fbb5c9a63.png">

This story allows the user to sort the projects by her/his preferences
In my app, the user won't (initially) be able to create her/his own tags, as this allows for consistency between users. Instead, a large number of possible tags will be given by the system.

# Acceptance criteria

- [x] Tags on Card are below the picture and horizontally scroll-able
- [x] Tags on the main site are in a cluster and not scroll-able (Design destined to change)
- [x] Selecting one changes the color to turquoise
- [x] Projects are filtered by how many selected tags apply to them, if zero -> not displayed
- [x] if no tags are selected, all projects are displayed

# Tasks

- [x] Add tags in the database, identical to those used by the cluster
- [x] Create `Tag` Component
- [x] Create `TagSection` on card for styling (flexbox, overflow: scroll)
- [x] Create `TagCluster`on main and include ~ 10 tags (category, type of business, continent, looking for, etc.)
- [x] Implement sorting algorithm (based on number of applying tags, highest to lowest) 
- [x] Tests

# Complexity
high
