### ISSUE TITLE
[Story] Search for projects

### ISSUE THREAD

**Issue by constantingoeldel** [constantingoeldel/capstone-project#3]
# Value statement

As a **user**
I need to **search**
so that I can **find projects I heard about, have an alternative to tags-filtering**

# Description (Text, Scribble, Wireframe, Design)

<img width="757" alt="image" src="https://user-images.githubusercontent.com/67916925/91315998-a1a27a00-e7b8-11ea-8970-527fbd4d6eba.png">

-  The search bar is the prominently placed uppermost item
-  Design inspired by Googles search bar, as this will be familiar to users

# Acceptance criteria

- [x] Placeholder text vanishes after initial input (But not by tapping  the field)
- [x] Every Input is instantly visible
- [x] Cards get reordered in real time
- [x] Press on the 'X' removes input
- [x] Results are ordered in respect to their similarity with the search terms -> Compared to full text
- [x] Search and filter function together

# Tasks

- [x] Research fuzzy search &&
- [x] Implement fuzzy search 
- [x] Create 'Search' Component consisting of 🔎 +  placeholder text and the X
- [x] Sort Array of cards by tags, then accuracy to search terms, most fitting at the beginning
- [x] Testing

# Complexity
high
