### ISSUE TITLE
[Story] Implement header

### ISSUE THREAD

**Issue by constantingoeldel** [constantingoeldel/capstone-project#4]
# Value statement

As a user
I need to see a header
so that I can orient myself

# Description (Text, Scribble, Wireframe, Design)
<img width="362" alt="image" src="https://user-images.githubusercontent.com/67916925/91320537-f09ede00-e7bd-11ea-96ae-6df34c358e19.png">
<img width="491" alt="image" src="https://user-images.githubusercontent.com/67916925/91320796-35c31000-e7be-11ea-896c-02d693b768ca.png">
**Design not final**
The header consists of the name of the page the user visits, as well as the users profile picture. 
Names of the other pages: 'My Projects', 'Opportunities', 'Profile'

# Acceptance criteria

- [ ] Header is fixed on top of the site 
- [ ] On top of all other content

# Tasks

- [ ] Create 'Header' Component
- [ ] Cypress Tests for visibility

# Complexity
Low
